### ISSUE TITLE
pdf generation error

### ISSUE THREAD

**Issue by chuanhua** [riscv/docs-templates#1]
When I used your listed command to generate a pdf file for the book_header.adoc, I encountered the following error.

Command: `asciidoctor-pdf book_header.adoc -a pdf-style#resources/themes/risc-v_spec-pdf.yml -a pdf-fontsdir=resources/fonts`
Error: `No such file or directory - notoserif-regular-subset.ttf not found in resources/fonts`

What should I do to eliminate this error?
Thanks!

**Comment by elisa-riscv** [comment]
My apologies for not seeing documentation of this error prior to today. This was my fault. Somehow a hashtag (#) was substituted for the equals sign (=) in the command.

I have corrected the command. In addition, since the time that you opened this issue, I have added information about getting the asciidoctor-diagram plugin working. 

So, without Wavedrom diagram scripts, use the same command but with the correction as follows:

asciidoctor-pdf book_header.adoc -a pdf-style=resources/themes/risc-v_spec-pdf.yml -a pdf-fontsdir=resources/fonts

And if you are using Wavedrom scripts in blocks that you want converted into diagrams:

asciidoctor-pdf -r asciidoctor-diagram book_header.adoc -a pdf-style=resources/themes/risc-v_spec-pdf.yml -a pdf-fontsdir=resources/fonts
